version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          working_directory: ~/WidgetExample
          name: Analyze on SonarCloud
          command: gradle build sonarqube -Dsonar.projectKey="darrellsnook_kotlin-android-examples" -Dsonar.organization="darrellsnook" -Dsonar.host.url="https://sonarcloud.io"
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
